### ISSUE TITLE
How does one copy over custom payload?

### ISSUE THREAD

**Issue by TheExpertNoob** [DavidBuchanan314/fusee-lede#1]
So, I flashed this with sysupgrade (from releases tab)
1) there is no /usr/share/fusee-nano directory
2) there is no ftp/sftp module installed (dropbear alone does not support sftp)
3) there is no usb modules installed (no sda listed with a fat32 drive inserted) (F2FS or fat32) (I do see usbcore and usb_common but no kmods supporting any kind of usb fs)
4) no LuCi GUI (which is expected due to 4mb of memory for this device)

Only way to recover is via flashing via serial. (that I can tell)

**Comment by DavidBuchanan314** [comment]
Hmm, there *should* be a `/usr/share/fusee-nano` directory, but maybe I messed something up.

It has a static IP of `192.168.1.1`, which you can connect to over ssh (and use scp to transfer files). (I should probably add this to the instructions)

**Comment by TheExpertNoob** [comment]
kinda retired my A5-V11 until now.
https://forum.piratebox.cc/read.php?22,21765
We will get this working.

**Comment by DavidBuchanan314** [comment]
Missing `/usr/share/fusee-nano` should have been fixed by https://github.com/DavidBuchanan314/fusee-lede/pull/2

**Comment by mariogamer2** [comment]
Can you add this to the instructions please?
